import type { Metadata } from "next";

// Supports weights 100-900
import '@fontsource-variable/inter';
// Supports weights 100-900
import '@fontsource-variable/kumbh-sans';
//import "@fontsource-variable/material-symbols-rounded";
import "@fontsource/material-symbols-rounded";


import "./globals.css";
import Header from "./components/headers/header";
import Footer from "./components/footers/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
